const String kBookBox = 'book_box';
const String kChapterBox = 'chapter_box';
const String kSavedVerses = 'dailyVerseSave';
const String kSavedBookNames = 'dailyBookNames';
const String kSavedVerseIDs = 'dailyVerseIDs';
const String kSavedChapterIDs = 'dailyChapterIDs';

const List<Map<String, dynamic>> booksData = [
  {'name': 'سفر التكوين', 'chapters': 50},
  {'name': 'سفر الخروج', 'chapters': 40},
  {'name': 'سفر اللاويين', 'chapters': 27},
  {'name': 'سفر العدد', 'chapters': 36},
  {'name': 'سفر التثنية', 'chapters': 34},
  {'name': 'سفر يشوع', 'chapters': 24},
  {'name': 'سفر القضاة', 'chapters': 21},
  {'name': 'سفر راعوث', 'chapters': 4},
  {'name': 'سفر صموئيل الأول', 'chapters': 31},
  {'name': 'سفر صموئيل الثاني', 'chapters': 24},
  {'name': 'سفر الملوك الأول', 'chapters': 22},
  {'name': 'سفر الملوك الثاني', 'chapters': 25},
  {'name': 'سفر أخبار الأيام الأول', 'chapters': 29},
  {'name': 'سفر أخبار الأيام الثاني', 'chapters': 36},
  {'name': 'سفر عزرا', 'chapters': 10},
  {'name': 'سفر نحميا', 'chapters': 13},
  {'name': 'سفر طوبيا', 'chapters': 14},
  {'name': 'سفر يهوديت', 'chapters': 16},
  {'name': 'سفر أستير', 'chapters': 10},
  {'name': 'تتمة سفر أستير', 'chapters': 7},
  {'name': 'سفر أيوب', 'chapters': 42},
  {'name': 'سفر المزامير', 'chapters': 150},
  {'name': 'المزمور المائة والحادي والخمسون', 'chapters': 1},
  {'name': 'سفر الأمثال', 'chapters': 31},
  {'name': 'سفر الجامعة', 'chapters': 12},
  {'name': 'سفر نشيد الأنشاد', 'chapters': 8},
  {'name': 'سفر الحكمة', 'chapters': 19},
  {'name': 'سفر يشوع بن سيراخ', 'chapters': 51},
  {'name': 'سفر إشعياء', 'chapters': 66},
  {'name': 'سفر إرميا', 'chapters': 52},
  {'name': 'سفر مراثي إرميا', 'chapters': 5},
  {'name': 'سفر باروخ', 'chapters': 6},
  {'name': 'سفر حزقيال', 'chapters': 48},
  {'name': 'سفر دانيال', 'chapters': 12},
  {'name': 'تتمة سفر دانيال', 'chapters': 3},
  {'name': 'سفر هوشع', 'chapters': 14},
  {'name': 'سفر يوئيل', 'chapters': 3},
  {'name': 'سفر عاموس', 'chapters': 9},
  {'name': 'سفر عوبديا', 'chapters': 1},
  {'name': 'سفر يونان', 'chapters': 4},
  {'name': 'سفر ميخا', 'chapters': 7},
  {'name': 'سفر ناحوم', 'chapters': 3},
  {'name': 'سفر حبقوق', 'chapters': 3},
  {'name': 'سفر صفنيا', 'chapters': 3},
  {'name': 'سفر حجي', 'chapters': 2},
  {'name': 'سفر زكريا', 'chapters': 14},
  {'name': 'سفر ملاخي', 'chapters': 4},
  {'name': 'سفر المكابيين الأول', 'chapters': 16},
  {'name': 'سفر المكابيين الثاني', 'chapters': 15},
  {'name': 'إنجيل متى', 'chapters': 28},
  {'name': 'إنجيل مرقس', 'chapters': 16},
  {'name': 'إنجيل لوقا', 'chapters': 24},
  {'name': 'إنجيل يوحنا', 'chapters': 21},
  {'name': 'سفر أعمال الرسل', 'chapters': 28},
  {'name': 'رسالة بولس الرسول إلى أهل رومية', 'chapters': 16},
  {'name': 'رسالة بولس الرسول الأولى إلى أهل كورنثوس', 'chapters': 16},
  {'name': 'رسالة بولس الرسول الثانية إلى أهل كورنثوس', 'chapters': 13},
  {'name': 'رسالة بولس الرسول إلى أهل غلاطية', 'chapters': 6},
  {'name': 'رسالة بولس الرسول إلى أهل أفسس', 'chapters': 6},
  {'name': 'رسالة بولس الرسول إلى أهل فيلبي', 'chapters': 4},
  {'name': 'رسالة بولس الرسول إلى أهل كولوسي', 'chapters': 4},
  {'name': 'رسالة بولس الرسول الأولى إلى أهل تسالونيكي', 'chapters': 5},
  {'name': 'رسالة بولس الرسول الثانية إلى أهل تسالونيكي', 'chapters': 3},
  {'name': 'رسالة بولس الرسول الأولى إلى تيموثاوس', 'chapters': 6},
  {'name': 'رسالة بولس الرسول الثانية إلى تيموثاوس', 'chapters': 4},
  {'name': 'رسالة بولس الرسول إلى تيطس', 'chapters': 3},
  {'name': 'رسالة بولس الرسول إلى فليمون', 'chapters': 1},
  {'name': 'رسالة بولس الرسول إلى العبرانيين', 'chapters': 13},
  {'name': 'رسالة يعقوب', 'chapters': 5},
  {'name': 'رسالة بطرس الرسول الأولى', 'chapters': 5},
  {'name': 'رسالة بطرس الرسول الثانية', 'chapters': 3},
  {'name': 'رسالة يوحنا الرسول الأولى', 'chapters': 5},
  {'name': 'رسالة يوحنا الرسول الثانية', 'chapters': 1},
  {'name': 'رسالة يوحنا الرسول الثالثة', 'chapters': 1},
  {'name': 'رسالة يهوذا', 'chapters': 1},
  {'name': 'سفر رؤيا يوحنا اللاه            وتي', 'chapters': 22},
];
