import 'package:versea/utils/data_source/local_data_source/bible_book_model.dart';

const List<BibleBookModel> bibleBooks = [
  BibleBookModel(id: 1, code: 'GEN', name: 'التكوين', chapters: 50),
  BibleBookModel(id: 2, code: 'EXO', name: 'الخروج', chapters: 40),
  BibleBookModel(id: 3, code: 'LEV', name: 'اللاويين', chapters: 27),
  BibleBookModel(id: 4, code: 'NUM', name: 'العدد', chapters: 36),
  BibleBookModel(id: 5, code: 'DEU', name: 'التثنية', chapters: 34),
  BibleBookModel(id: 6, code: 'JOS', name: 'يشوع', chapters: 24),
  BibleBookModel(id: 7, code: 'JDG', name: 'القضاة', chapters: 21),
  BibleBookModel(id: 8, code: 'RUT', name: 'راعوث', chapters: 4),
  BibleBookModel(id: 9, code: '1SA', name: 'صموئيل الأول', chapters: 31),
  BibleBookModel(id: 10, code: '2SA', name: 'صموئيل الثاني', chapters: 24),
  BibleBookModel(id: 11, code: '1KI', name: 'الملوك الأول', chapters: 22),
  BibleBookModel(id: 12, code: '2KI', name: 'الملوك الثاني', chapters: 25),
  BibleBookModel(id: 13, code: '1CH', name: 'أخبار الأيام الأول', chapters: 29),
  BibleBookModel(
    id: 14,
    code: '2CH',
    name: 'أخبار الأيام الثاني',
    chapters: 36,
  ),
  BibleBookModel(id: 15, code: 'EZR', name: 'عزرا', chapters: 10),
  BibleBookModel(id: 16, code: 'NEH', name: 'نحميا', chapters: 13),
  BibleBookModel(id: 17, code: 'EST', name: 'أستير', chapters: 10),
  BibleBookModel(id: 18, code: 'JOB', name: 'أيوب', chapters: 42),
  BibleBookModel(id: 19, code: 'PSA', name: 'المزامير', chapters: 150),
  BibleBookModel(id: 20, code: 'PRO', name: 'الأمثال', chapters: 31),
  BibleBookModel(id: 21, code: 'ECC', name: 'الجامعة', chapters: 12),
  BibleBookModel(id: 22, code: 'SNG', name: 'نشيد الأنشاد', chapters: 8),
  BibleBookModel(id: 23, code: 'ISA', name: 'إشعياء', chapters: 66),
  BibleBookModel(id: 24, code: 'JER', name: 'إرميا', chapters: 52),
  BibleBookModel(id: 25, code: 'LAM', name: 'مراثي إرميا', chapters: 5),
  BibleBookModel(id: 26, code: 'EZK', name: 'حزقيال', chapters: 48),
  BibleBookModel(id: 27, code: 'DAN', name: 'دانيال', chapters: 12),
  BibleBookModel(id: 28, code: 'HOS', name: 'هوشع', chapters: 14),
  BibleBookModel(id: 29, code: 'JOL', name: 'يوئيل', chapters: 3),
  BibleBookModel(id: 30, code: 'AMO', name: 'عاموس', chapters: 9),
  BibleBookModel(id: 31, code: 'OBA', name: 'عوبديا', chapters: 1),
  BibleBookModel(id: 32, code: 'JON', name: 'يونان', chapters: 4),
  BibleBookModel(id: 33, code: 'MIC', name: 'ميخا', chapters: 7),
  BibleBookModel(id: 34, code: 'NAM', name: 'ناحوم', chapters: 3),
  BibleBookModel(id: 35, code: 'HAB', name: 'حبقوق', chapters: 3),
  BibleBookModel(id: 36, code: 'ZEP', name: 'صفنيا', chapters: 3),
  BibleBookModel(id: 37, code: 'HAG', name: 'حجي', chapters: 2),
  BibleBookModel(id: 38, code: 'ZEC', name: 'زكريا', chapters: 14),
  BibleBookModel(id: 39, code: 'MAL', name: 'ملاخي', chapters: 4),
  BibleBookModel(id: 40, code: 'MAT', name: 'متى', chapters: 28),
  BibleBookModel(id: 41, code: 'MRK', name: 'مرقس', chapters: 16),
  BibleBookModel(id: 42, code: 'LUK', name: 'لوقا', chapters: 24),
  BibleBookModel(id: 43, code: 'JHN', name: 'يوحنا', chapters: 21),
  BibleBookModel(id: 44, code: 'ACT', name: 'أعمال الرسل', chapters: 28),
  BibleBookModel(id: 45, code: 'ROM', name: 'رومية', chapters: 16),
  BibleBookModel(id: 46, code: '1CO', name: 'كورنثوس الأولى', chapters: 16),
  BibleBookModel(id: 47, code: '2CO', name: 'كورنثوس الثانية', chapters: 13),
  BibleBookModel(id: 48, code: 'GAL', name: 'غلاطية', chapters: 6),
  BibleBookModel(id: 49, code: 'EPH', name: 'أفسس', chapters: 6),
  BibleBookModel(id: 50, code: 'PHP', name: 'فيلبي', chapters: 4),
  BibleBookModel(id: 51, code: 'COL', name: 'كولوسي', chapters: 4),
  BibleBookModel(id: 52, code: '1TH', name: 'تسالونيكي الأولى', chapters: 5),
  BibleBookModel(id: 53, code: '2TH', name: 'تسالونيكي الثانية', chapters: 3),
  BibleBookModel(id: 54, code: '1TI', name: 'تيموثاوس الأولى', chapters: 6),
  BibleBookModel(id: 55, code: '2TI', name: 'تيموثاوس الثانية', chapters: 4),
  BibleBookModel(id: 56, code: 'TIT', name: 'تيطس', chapters: 3),
  BibleBookModel(id: 57, code: 'PHM', name: 'فليمون', chapters: 1),
  BibleBookModel(id: 58, code: 'HEB', name: 'العبرانيين', chapters: 13),
  BibleBookModel(id: 59, code: 'JAS', name: 'يعقوب', chapters: 5),
  BibleBookModel(id: 60, code: '1PE', name: 'بطرس الأولى', chapters: 5),
  BibleBookModel(id: 61, code: '2PE', name: 'بطرس الثانية', chapters: 3),
  BibleBookModel(id: 62, code: '1JN', name: 'يوحنا الأولى', chapters: 5),
  BibleBookModel(id: 63, code: '2JN', name: 'يوحنا الثانية', chapters: 1),
  BibleBookModel(id: 64, code: '3JN', name: 'يوحنا الثالثة', chapters: 1),
  BibleBookModel(id: 65, code: 'JUD', name: 'يهوذا', chapters: 1),
  BibleBookModel(id: 66, code: 'REV', name: 'الرؤيا', chapters: 22),
];
