// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp2UH1WznBPStuSP5uiQikdt8ovpptCuo',
    appId: '1:22694069:web:35acf12367975e0aa316fc',
    messagingSenderId: '22694069',
    projectId: 'versea-e29cb',
    authDomain: 'versea-e29cb.firebaseapp.com',
    storageBucket: 'versea-e29cb.firebasestorage.app',
    measurementId: 'G-96JRK7WSC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVyqEwyuaDNWzhDrbJ8HCra7DrAS8Z6C0',
    appId: '1:22694069:android:1daeaf04b56371a0a316fc',
    messagingSenderId: '22694069',
    projectId: 'versea-e29cb',
    storageBucket: 'versea-e29cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZJoFOK9zXf-tJX3JiIMgAMlnN7lkxUVM',
    appId: '1:22694069:ios:d0effe59925b90a5a316fc',
    messagingSenderId: '22694069',
    projectId: 'versea-e29cb',
    storageBucket: 'versea-e29cb.firebasestorage.app',
    iosBundleId: 'com.example.versea',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZJoFOK9zXf-tJX3JiIMgAMlnN7lkxUVM',
    appId: '1:22694069:ios:d0effe59925b90a5a316fc',
    messagingSenderId: '22694069',
    projectId: 'versea-e29cb',
    storageBucket: 'versea-e29cb.firebasestorage.app',
    iosBundleId: 'com.example.versea',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp2UH1WznBPStuSP5uiQikdt8ovpptCuo',
    appId: '1:22694069:web:54972a0764f61ec5a316fc',
    messagingSenderId: '22694069',
    projectId: 'versea-e29cb',
    authDomain: 'versea-e29cb.firebaseapp.com',
    storageBucket: 'versea-e29cb.firebasestorage.app',
    measurementId: 'G-5K6FTBEEJK',
  );
}
